steps:
# This step uses Buildpacks to build your application from the 'templates' directory
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: pack
  args:
  - build
  # Define the name for the container image that will be built.
  # Uses your Project ID and substitutes repo, branch, and commit info.
  - 'gcr.io/lauravoiceassistant-452622/$REPO_NAME/$BRANCH_NAME:$COMMIT_SHA' # Project ID is updated here
  # Specify the standard Google Cloud Buildpacks builder
  - --builder=gcr.io/buildpacks/builder
  # Specify the path to your application code relative to the repository root
  - --path=templates

# Specify the image(s) to push to Google Container Registry (GCR) after building.
# This must match the image name defined in the 'pack build' step above.
images:
- 'gcr.io/lauravoiceassistant-452622/$REPO_NAME/$BRANCH_NAME:$COMMIT_SHA' # Project ID is updated here

# Set build options
options:
  # Use Cloud Logging only to avoid issues with GCS bucket permissions for logs.
  logging: CLOUD_LOGGING_ONLY
